# Generated by Django 3.1.7 on 2021-03-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='ticker',
            field=models.CharField(default='VTI', max_length=5),
        ),
    ]
