# Generated by Django 3.1.7 on 2021-03-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_signup_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='strategy',
            field=models.CharField(choices=[('GC', 'Golden Cross'), ('ATR', 'ATR Limit Order')], default='GC', max_length=100),
        ),
    ]
